### ISSUE TITLE
Support for soft deletes

### ISSUE THREAD

**Issue by MatiasOlivera** [MatiasOlivera/feedy#1]
### Actual Behavior
The type resolvers fail when try to fetch the row from the database because it no longer exists anymore. Values are not returned from the second nesting level.
### Expected Behavior
Be able to solve all values regardless of the level of nesting in mutations that erases records.
### Todo
- [x] Add deleted_at column in all tables
- [x] Add support for soft deletes in the models
- [x] Use the correct method in delete mutations
- [x] Add deletedAt property in all GraphQL types
- [x] Add restore mutation to all types
- [x] Add a filter to queries to get active or deleted instances
